# Usa la imagen de Tomcat 8.5.84-jdk8-openjdk como base
FROM tomcat:8.5.84-jdk8-openjdk

# Copia el archivo WAR de tu aplicación al directorio webapps de Tomcat
COPY target/ConsultorioOdontologiaFinal-1.0.war /usr/local/tomcat/webapps/

# Puerto que expondrá la aplicación web
EXPOSE 8080

# Copiar el script de inicio personalizado dentro de la imagen Docker
COPY ./apache-tomcat-8.5.84/bin/startup.bat /usr/local/tomcat/bin/startup.bat

# Dar permisos de ejecución al script de inicio
RUN chmod +x /usr/local/tomcat/bin/startup.bat

# Comando para ejecutar Tomcat (iniciará la aplicación web automáticamente)
CMD ["/usr/local/tomcat/bin/startup.bat", "run"]
