# Usa la imagen de Tomcat 9.0.85-jdk8-openjdk como base
FROM tomcat:9.0.85-jdk8-openjdk

# Copia el archivo WAR de tu aplicación al directorio webapps de Tomcat
COPY target/ConsultorioOdontologiaFinal-1.0.war /usr/local/tomcat/webapps/

# Puerto que expondrá la aplicación web
EXPOSE 8080

# Comando para ejecutar Tomcat (iniciará la aplicación web automáticamente)
CMD ["startup.bat", "run"]
